services:
  backend:
    build:
      context: . 
      dockerfile: Dockerfile 
    ports:
      - "${HOST_PORT:-3000}:${BACKEND_PORT:-3000}" 
    environment:
      MONGO_URL: ${MONGO_URL:-mongodb://mongodb:27017/myauthapp}
      JWT_SECRET: ${JWT_SECRET}
      PORT: ${BACKEND_PORT:-3000} 
    depends_on:
      - mongodb 

  mongodb:
    image: mongo:latest 
    ports:
      - "27017:27017" 
    volumes:
      - mongo_data:/data/db 

volumes:
  mongo_data: 